export const users = [
   {
      id: 1,
      created_at: '2024-01-01T00:00:00.000Z',
      email: 'jSb0U@example.com',
      password: 'password123',
      full_name: 'John Doe',
      is_admin: false,
   },
   {
      id: 2,
      created_at: '2024-01-04T00:00:00.000Z',
      email: 'jSuub0U@example.com',
      password: 'password123',
      full_name: 'Will Smith',
      is_admin: false,
   },
   {
      id: 3,
      created_at: '2024-01-05T00:00:00.000Z',
      email: 'jSbuiuii0U@example.com',
      password: 'password123',
      full_name: 'Jane Doe',
      is_admin: false,
   },
   {
      id: 4,
      created_at: '2024-01-06T00:00:00.000Z',
      email: 'jSbiui0U@example.com',
      password: 'password123',
      full_name: 'Bob Smith',
      is_admin: false,
   },
   {
      id: 5,
      created_at: '2024-01-07T00:00:00.000Z',
      email: 'jShub0U@example.com',
      password: 'password123',
      full_name: 'Alice Smith',
      is_admin: false,
   },
   {
      id: 6,
      email: 'jShhh0U@example.com',
      password: 'password123',
      full_name: 'Tom Smith',
      is_admin: false,
   },
   {
      id: 7,
      email: 'jSbppp0U@example.com',
      password: 'password123',
      full_name: 'Pat Smith',
      is_admin: false,
   },
];
